### ISSUE TITLE
[Fixed] [Awaiting Response] Unable to launch edge with no arguments/ Edge stops working after update.

### ISSUE THREAD

**Issue by ferrazpedro** [HarshalKudale/NoMoreEdge#8] opened 2021-12-12 14:34 UTC
Hey! I was testing your app and after installing it Edge doesn't launch anymore. Is this te expected behavior? I was expecting it to redirect links to my default browser, but that I could launch Edge whenever I wanted too.

**Comment by HarshalKudale** [comment] 2021-12-12 17:47
This is not expected behaviour. I added edge support in latest update. Also can you please provide steps to reproduce. Just to be sure please reinstall application once from latest release.

**Comment by totallygeekdom** [comment] 2021-12-12 19:07
yup just had the same issue.

**Comment by HarshalKudale** [comment] 2021-12-12 19:35
> yup just had the same issue.
Please reply with build number of windows 11.
Can you please check if NoMoreEdge is running in task manager (Both in apps and processes) after launching edge. Also please confirm you default browser in settings for http and https.I still recommend uninstalling and reinstalling the once. I am currently looking into problem.

**Comment by totallygeekdom** [comment] 2021-12-12 19:59
> > yup just had the same issue.
> > Please reply with build number of windows 11.
> > Can you please check if NoMoreEdge is running in task manager (Both in apps and processes) after launching edge. Also please confirm you default browser in settings for http and https.I still recommend uninstalling and reinstalling the once. I am currently looking into problem.

Hello thanks for getting back to me. I am running the latest beta build of windows or build #22000.348
my default browser is opera gx stable for both HTTP and HTTPS
It doesn't look like no more edge is running in apps or processes

Also to further explain the problem edge for me will still work after installing no more edge but the browser will progressively continue to get slower and unresponsive. Then it just won't launch. Restarting the computer or reinstalling edge will not fix the problem; only uninstalling no more edge will fix it. This has happened to me twice. For now, I will keep no more edge uninstalled to see if I encounter further issues with edge; so I can further identify the issue.

**Comment by totallygeekdom** [comment] 2021-12-12 20:04
> > yup just had the same issue.
> > Please reply with build number of windows 11.
> > Can you please check if NoMoreEdge is running in task manager (Both in apps and processes) after launching edge. Also please confirm you default browser in settings for http and https.I still recommend uninstalling and reinstalling the once. I am currently looking into problem.

I also get this error message when trying to uninstall no more edge
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge_backup.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at NoMoreEdgeSetup.NoMoreEdgeSetupForm.uninstallApp(String path, String newedge)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NoMoreEdgeSetup
    Assembly Version: 1.5.0.3
    Win32 Version: 1.5.0.3
    CodeBase: file:///C:/Users/ryanl/Downloads/NoMoreEdgeSetup.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ferrazpedro** [comment] 2021-12-12 20:51
> > > yup just had the same issue.
> > > Please reply with build number of windows 11.
> > > Can you please check if NoMoreEdge is running in task manager (Both in apps and processes) after launching edge. Also please confirm you default browser in settings for http and https.I still recommend uninstalling and reinstalling the once. I am currently looking into problem.
> 
> Hello thanks for getting back to me. I am running the latest beta build of windows or build #22000.348 my default browser is opera gx stable for both HTTP and HTTPS It doesn't look like no more edge is running in apps or processes
> 
> Also to further explain the problem edge for me will still work after installing no more edge but the browser will progressively continue to get slower and unresponsive. Then it just won't launch. Restarting the computer or reinstalling edge will not fix the problem; only uninstalling no more edge will fix it. This has happened to me twice. For now, I will keep no more edge uninstalled to see if I encounter further issues with edge; so I can further identify the issue.

This is exactly the same problem I've been having! If Edge is open when I install NoMoreEdge it gets slower and slower until it doesn't work anymore. If I try to launch Edge from the start menu after I close it for the first time, nothing happens.

If I uninstall NoMoreEdge, it works fine again. I`m using Windows 11 build 22000.348

EDIT: Btw, the version i've tested was the 1.5.0.3

**Comment by totallygeekdom** [comment] 2021-12-12 20:54
> > > > yup just had the same issue.
> > > > Please reply with build number of windows 11.
> > > > Can you please check if NoMoreEdge is running in task manager (Both in apps and processes) after launching edge. Also please confirm you default browser in settings for http and https.I still recommend uninstalling and reinstalling the once. I am currently looking into problem.
> > 
> > 
> > Hello thanks for getting back to me. I am running the latest beta build of windows or build #22000.348 my default browser is opera gx stable for both HTTP and HTTPS It doesn't look like no more edge is running in apps or processes
> > Also to further explain the problem edge for me will still work after installing no more edge but the browser will progressively continue to get slower and unresponsive. Then it just won't launch. Restarting the computer or reinstalling edge will not fix the problem; only uninstalling no more edge will fix it. This has happened to me twice. For now, I will keep no more edge uninstalled to see if I encounter further issues with edge; so I can further identify the issue.
> 
> This is exactly the same problem I've been having! If Edge is open when I install NoMoreEdge it gets slower and slower until it doesn't work anymore. If I try to launch Edge from the start menu after I close it for the first time, nothing happens.
> 
> If I uninstall NoMoreEdge, it works fine again. I`m using Windows 11 build 22000.348

thank you I am glad to know I'm not the only one experiencing the issue.

**Comment by HarshalKudale** [comment] 2021-12-13 03:05
> > > yup just had the same issue.
> > > Please reply with build number of windows 11.
> > > Can you please check if NoMoreEdge is running in task manager (Both in apps and processes) after launching edge. Also please confirm you default browser in settings for http and https.I still recommend uninstalling and reinstalling the once. I am currently looking into problem.
> 
> I also get this error message when trying to uninstall no more edge See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text ************** System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge_backup.exe' is denied. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.File.InternalDelete(String path, Boolean checkHost) at NoMoreEdgeSetup.NoMoreEdgeSetupForm.uninstallApp(String path, String newedge) at System.Windows.Forms.Control.OnClick(EventArgs e) at System.Windows.Forms.Button.OnClick(EventArgs e) at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent) at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks) at System.Windows.Forms.Control.WndProc(Message& m) at System.Windows.Forms.ButtonBase.WndProc(Message& m) at System.Windows.Forms.Button.WndProc(Message& m) at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> ## ************** Loaded Assemblies **************
> mscorlib
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ## NoMoreEdgeSetup
> Assembly Version: 1.5.0.3
> Win32 Version: 1.5.0.3
> CodeBase: file:///C:/Users/ryanl/Downloads/NoMoreEdgeSetup.exe
> ## System.Windows.Forms
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ## System
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ## System.Drawing
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ## System.Configuration
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ## System.Core
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ## System.Xml
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4161.0 built by: NET48REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ## Accessibility
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4161.0 built by: NET48REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ************** JIT Debugging ************** To enable just-in-time (JIT) debugging, the .config file for this application or computer (machine.config) must have the jitDebugging value set in the system.windows.forms section. The application must also be compiled with debugging enabled.
> 
> For example:
> 
> When JIT debugging is enabled, any unhandled exception will be sent to the JIT debugger registered on the computer rather than be handled by this dialog box.

This exception happens when uninstalling NoMoreEdge while edge is open. Reason for this is NoMoreEdge creates copy of msedge as msedge_backup.exe . which is used for normal edge usage and it must be deleted while uninstalling NoMoreEdge. But as this exe is open under edge process NoMoreEdge can not delete it and it gives error.

**Comment by HarshalKudale** [comment] 2021-12-13 03:07
> > > yup just had the same issue.
> > > Please reply with build number of windows 11.
> > > Can you please check if NoMoreEdge is running in task manager (Both in apps and processes) after launching edge. Also please confirm you default browser in settings for http and https.I still recommend uninstalling and reinstalling the once. I am currently looking into problem.
> 
> Hello thanks for getting back to me. I am running the latest beta build of windows or build #22000.348 my default browser is opera gx stable for both HTTP and HTTPS It doesn't look like no more edge is running in apps or processes
> 
> Also to further explain the problem edge for me will still work after installing no more edge but the browser will progressively continue to get slower and unresponsive. Then it just won't launch. Restarting the computer or reinstalling edge will not fix the problem; only uninstalling no more edge will fix it. This has happened to me twice. For now, I will keep no more edge uninstalled to see if I encounter further issues with edge; so I can further identify the issue.

I will look into issue more and try to find what exactly is happening. Thank you for trying the software. I will keep updating in this issue thread.

**Comment by HarshalKudale** [comment] 2021-12-15 10:51
Issue has been identified. Edge stops working after every update. I will look into this once new edge update drops.

**Comment by HarshalKudale** [comment] 2021-12-16 15:57
@ferrazpedro @totallygeekdom I found the cause of issue. I will drop the update after cleaning debug code. Read below.

The problem was that every time edge was getting updated msedge_backup.exe was becoming obsolete. So I have added hash check for Normal edge launch. So that every time you launch edge it will check hash for msedge.exe(updated) with msedge_backup.exe(created while installing). If the hash matches it will launch edge and if they don't it will ask for admin permission in order to patch new version. After than you can use edge normally. I will close the issue once update drops.

Thank you for informing the issue.

**Comment by cztbg0** [comment] 2021-12-17 02:08
> @ferrazpedro @totallygeekdom I found the cause of issue. I will drop the update after cleaning debug code. Read below.
> 
> The problem was that every time edge was getting updated msedge_backup.exe was becoming obsolete. So I have added hash check for Normal edge launch. So that every time you launch edge it will check hash for msedge.exe(updated) with msedge_backup.exe(created while installing). If the hash matches it will launch edge and if they don't it will ask for admin permission in order to patch new version. After than you can use edge normally. I will close the issue once update drops.
> 
> Thank you for informing the issue.

The msedge_backup.exe error was also occurring in windows 10, and a quick workaround was to rename the folder in question. In my case, Windows was indicating it could not find version 96.0.1054.53 and the folder edge had updated to was 96.0.1054.57. 

Renaming the folder fixed the issue in the short term. Thanks for working on a permanent fix.

**Comment by HarshalKudale** [comment] 2021-12-17 06:29
> 

I am currently testing some other fixes along with this one. Will update once its done.

**Comment by totallygeekdom** [comment] 2021-12-17 09:14
Thank you for doing this. I appreciate it.

**Comment by Yannik** [comment] 2021-12-18 14:30
@HarshalKudale 

I would recommend looking into how @aveyo is solving this in https://github.com/AveYo/fox/blob/main/ChrEdgeFkOff.cmd. They are creating a link `C:\Program Files (x86)\Microsoft\ChrEdge` which has `C:\Program Files (x86)\Microsoft\Edge` as its target. To avoid IFEO loops, they are calling `C:\Program Files (x86)\Microsoft\ChrEdge\Application\msedge.exe` inside their script to start edge.

This is update-proof and much easier than checking hashes and creating new `msedge_backup.exe` files whenever `msedge.exe` has been changed (which would also not work with normal user priviliges!).

I believe this is a far better solution!

Edit: The command they are using for this is `mklink /J <EDGE-FOLDER-COPY> <REAL-EDGE-FOLDER>`

**Comment by Yannik** [comment] 2021-12-18 14:39
@HarshalKudale I would also like to make another suggestion: 

Please make it possible to **not** use the fallback of starting edge for non-`microsoft-edge:` calls. (i.e. redirecting spotlight searches, but blocking edge usage)

**Comment by HarshalKudale** [comment] 2021-12-18 16:14
> @HarshalKudale
> 
> I would recommend looking into how @AveYo is solving this in https://github.com/AveYo/fox/blob/main/ChrEdgeFkOff.cmd. They are creating a link `C:\Program Files (x86)\Microsoft\ChrEdge` which has `C:\Program Files (x86)\Microsoft\Edge` as its target. To avoid IFEO loops, they are calling `C:\Program Files (x86)\Microsoft\ChrEdge\Application\msedge.exe` inside their script to start edge.
> 
> This is update-proof and much easier than checking hashes and creating new `msedge_backup.exe` files whenever `msedge.exe` has been changed (which would also not work with normal user priviliges!).
> 
> I believe this is a far better solution!
> 
> Edit: The command they are using for this is `mklink /J <EDGE-FOLDER-COPY> <REAL-EDGE-FOLDER>`

I tried to understand the codes but its beyond my understanding. I would contact the developer see if I can get some help. Thank you for suggestion.

**Comment by HarshalKudale** [comment] 2021-12-18 16:15
> @HarshalKudale I would also like to make another suggestion:
> 
> Please make it possible to **not** use the fallback of starting edge for non-`microsoft-edge:` calls. (i.e. redirecting spotlight searches, but blocking edge usage)

Please describe issue / feature request in detail. I am unable to understand. NoMoreEdge is already redirecting spotlight urls(image searches ) to default browser.

**Comment by Yannik** [comment] 2021-12-18 16:59
> 



> > @HarshalKudale
> > I would recommend looking into how @AveYo is solving this in https://github.com/AveYo/fox/blob/main/ChrEdgeFkOff.cmd. They are creating a link `C:\Program Files (x86)\Microsoft\ChrEdge` which has `C:\Program Files (x86)\Microsoft\Edge` as its target. To avoid IFEO loops, they are calling `C:\Program Files (x86)\Microsoft\ChrEdge\Application\msedge.exe` inside their script to start edge.
> > This is update-proof and much easier than checking hashes and creating new `msedge_backup.exe` files whenever `msedge.exe` has been changed (which would also not work with normal user priviliges!).
> > I believe this is a far better solution!
> > Edit: The command they are using for this is `mklink /J <EDGE-FOLDER-COPY> <REAL-EDGE-FOLDER>`
> 
> I tried to understand the codes but its beyond my understanding. I would contact the developer see if I can get some help. Thank you for suggestion.

Yeah, that code is really hard to understand.
The script basically does three things: 
 - Create the IFEO registry keys
 - Create the link I described above from `C:\Program Files (x86)\Microsoft\ChrEdge` to `C:\Program Files (x86)\Microsoft\Edge`
 - Create a `ChrEdgeFkOff.vbs` script in `C:\ProgramData\`
 I have had an attempt to make the `ChrEdgeFkOff.vbs` more readable:
 
 ``` 
 ' ChrEdgeFkOff - make start menu web search or widgets links open in your chosen default browser - by AveYo 
Dim PSCommand, QuotedCommand
For Each arg in WScript.Arguments
QuotedCommand = QuotedCommand&" """&arg&""""
Next

Set Shell = CreateObject("WScript.Shell")
Set Env = Shell.Environment( "Process" )

' Write Commandline including arguments to variable
Env("QuotedCommand") = QuotedCommand

PSCommand = ""
PSCommand = PSCommand & "$UserChoiceBrowserProgId = get-itemproperty 'HKCU:\SOFTWARE\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice' 'ProgID';"
PSCommand = PSCommand & "$UserChoiceBrowserCmd = get-itemproperty -lit $('Registry::HKCR\' + $UserChoiceBrowserProgId.ProgId + '\shell\open\command') '(Default)' -ea 0;"
PSCommand = PSCommand & "$UserChoiceBrowserPath = ($UserChoiceBrowserCmd.'(Default)'-split [char]34,3)[1];"
PSCommand = PSCommand & "$MSE = $env:QuotedCommand -replace '\\Microsoft\\Edge', '\Microsoft\ChrEdge';"
PSCommand = PSCommand & "if ($UserChoiceBrowserPath -like '*Microsoft\Edge\Application\msedge.exe*') {Invoke-Expression('&'+$MSE); return 2};"
PSCommand = PSCommand & "if ($env:QuotedCommand -notlike '*microsoft-edge:*') {Invoke-Expression('&'+$MSE); return 1};"
PSCommand = PSCommand & "start $UserChoiceBrowserPath $([uri]::unescapedatastring(($env:QuotedCommand-split'(?=http[s]?)')[1] -replace [char]34)+' '); return 0"
Shell.Run "powershell -nop -c " & PSCommand, 0, False
```
 
 Now, the part that I would suggest copying is using a link instead of copying `msedge.exe`. 
 
 This fixes the issues on update that are currently occuring.

**Comment by Yannik** [comment] 2021-12-18 17:02
> > @HarshalKudale I would also like to make another suggestion:
> > Please make it possible to **not** use the fallback of starting edge for non-`microsoft-edge:` calls. (i.e. redirecting spotlight searches, but blocking edge usage)
> 
> Please describe issue / feature request in detail. I am unable to understand. NoMoreEdge is already redirecting spotlight urls(image searches ) to default browser.

Yes, I know it does. However, in [all other cases](https://github.com/HarshalKudale/NoMoreEdge/blob/master/NoMoreEdge.cs#L121), you are [starting](https://github.com/HarshalKudale/NoMoreEdge/blob/master/NoMoreEdge.cs#L143) edge. I would like an option to simply `return` in that case (not starting edge!).

**Comment by Yannik** [comment] 2021-12-18 17:11
@HarshalKudale Ah, I think another critical thing is that @aveyo is setting the IFEO `FilterFullPath` option. Otherwise, there would be an IFEO loop.

**Comment by HarshalKudale** [comment] 2021-12-18 17:39
> 

So, after 3 hours of reading script and googling power script I have managed to understand what exactly is happening. It is really easy to implement for me in C#. I will start working one this . Thank you for all help and explanation. NoMoreEdge will not need vbs script. 

Edit- Just read your comments above. It looks like you just want to nuke edge altogether with still having ability to redirect searches. Sure I will add ability to just get dump the windows call when its not microsoft-edge:// call. Also I am currently not coding so it will take time to implement.

**Comment by Yannik** [comment] 2021-12-18 17:48
@HarshalKudale Great! I'm looking forwarding to testing it!

**Comment by Yannik** [comment] 2021-12-18 17:51
> Edit- Just read your comments above. It looks like you just want to nuke edge altogether with still having ability to redirect searches. Sure I will add ability to just get dump the windows call when its not microsoft-edge:// call. Also I am currently not coding so it will take time to implement.

Yeah, exactly!

**Comment by AveYo** [comment] 2021-12-18 19:19
@Yannik 
>Yeah, that code is really hard to understand.

That's unfounded, since you managed just fine. But your breakdown does not really make it more clear. 
It's a 3-in-1 hybrid script, that's the more intimidating part for those unfamiliar with scripting.
So it needs to be pealed off in layers based on language used ;)

1st, it's the cmd/ps line that will send everything written to powershell then some comments 
``` bat
@(set "0=%~f0"^)#) & powershell -nop -c iex([io.file]::ReadAllText($env:0)) & exit/b
```

2nd, it's the auto-elevate powershell snippet as an outer-layer. since variables are not passed to an elevated process by design, it makes things a bit more convoluted than it should need to be  
``` ps1
$_Paste_in_Powershell = {
[..]
} ; start -verb runas powershell -args "-nop -c & {`n`n$($_Paste_in_Powershell-replace'"','\"')}"
```

3rd, it's the inner, elevated powershell code responsible for install and uninstall. 
Basic dynamic directories for x86 and x64 os, ifeo setup, and it includes the whole "redirector" vbs file content
``` ps1
$vbs = [...]
$DATA = [Environment]::GetFolderPath('CommonApplicationData'); $file = join-path $DATA "ChrEdgeFkOff.vbs"
$PROF = [Environment]::GetFolderPath('ProgramFiles'+('x86','')[![Environment]::Is64BitOperatingSystem])
$EDGE = join-path $PROF 'Microsoft\Edge\'; $CREDGE = join-path $PROF 'Microsoft\ChrEdge\'
$IFEO = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe'
if (test-path "$IFEO\0") {
  remove-item "$IFEO\0" -rec -force -ea 0 >''; remove-itemproperty $IFEO 'Debugger' -force -ea 0 >'' 
  del $file -force -ea 0 >''; rmdir $CREDGE -rec -force -ea 0 >'';
  write-host -fore 0xf -back 0xd "`n ChrEdgeFkOff v2.0 [REMOVED] run again to install "
} else {                              
  new-item "$IFEO\0" -force -ea 0 >''; remove-itemproperty $IFEO 'Debugger' -force -ea 0 >'' 
  [io.file]::WriteAllText($file, $vbs) >''; start -nonew cmd "/d/x/r mklink /J ""$CREDGE"" ""$EDGE"" >nul"
  set-itemproperty $IFEO 'UseFilter' 1 -type dword -force -ea 0
  set-itemproperty "$IFEO\0" 'FilterFullPath' $(join-path $PROF 'Microsoft\Edge\Application\msedge.exe') -force -ea 0 
  set-itemproperty "$IFEO\0" 'Debugger' "wscript $file //B //T:5" -force -ea 0 
  write-host -fore 0xf -back 0x2 "`n ChrEdgeFkOff v2.0 [INSTALLED] run again to remove " } ; timeout /t 5
}
```

4th, the "redirector" vbs file wrapper is used just to hide the powershell window, could very well just use powershell only, and even add it directly to the reg key and not need a file at all, (like I do in Skip_TPM_Check_on_Dynamic_Update.cmd) but then a ps window would briefly flash whenever redirection would happen  
``` vbs
Dim C, A: For Each i in WScript.Arguments: A = A&" """&i&"""": Next
Set W = CreateObject("WScript.Shell"): Set E = W.Environment( "Process" ): E("CL") = A : C = ""
C = [..]
W.Run "powershell -nop -c " & C, 0, False
```

5th is the "redirector" powershell code
``` ps1
$U = get-itemproperty 'HKCU:\SOFTWARE\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice' 'ProgID';
$C = get-itemproperty -lit $('Registry::HKCR\' + $U.ProgID + '\shell\open\command') '(Default)' -ea 0;
$UserChoice = ($C.'(Default)'-split [char]34,3)[1]; $MSE = $env:CL -replace '\\Microsoft\\Edge', '\Microsoft\ChrEdge';
if ($UserChoice -like '*Microsoft\Edge\Application\msedge.exe*') {iex('&'+$MSE); return 2};
if ($env:CL -notlike '*microsoft-edge:*') {iex('&'+$MSE); return 1};
start $UserChoice $([uri]::unescapedatastring(($env:CL-split'(?=http[s]?)')[1] -replace [char]34)+' '); return 0
```

For someone familiar with powershell syntax, it's easy to understand what it does and how it does it, and even if not familiar, ~~google~~ bing (hehe) is very helpful. And while a longer variable name might appear more descriptive, I think $U in the same line with UserChoice, $C with open\command, $UserChoice and $MSE get the idea across. Then there are some syntactic sugar here and there, specially taking into account that passing quotes across 3 different shells (cmd, powershell, vbs) is also harder than it needs to be, by microsoft design.
I could have written everything following microsoft bloat style in 300-3000 lines with mostly whitespace, but I choose not to. 
I find it much easier and faster to understand a mere 30 short lines of code than a wall of it, sometimes split into dozens other files _(useless modules, classes interfaces etc for something that will never be extended)_ that I have to scroll up and down and can't get a bird's eye view. 
If you inspect xxx.exe I can guarantee you won't find it better to read, it's a binary, not full plain-text open source from start to finish which is how any os tweaking should come. How many times do you compile stuff yourself vs trusting the whatever precompiled binary release of authors? Hardly ever. This is not a bashing of the current project, it's simply a general observation.
Anyway, not to brag or anything but my stuff is usually golden, ready to be copy-pasted in a powershell console directly without caution ;)
Good luck @HarshalKudale! 
_PS. [I've asked you to update the comparison table for the IFEO looping support](https://github.com/HarshalKudale/NoMoreEdge/commit/0d87fb70ef68299a04862a980b92ee3dcb148f64#commitcomment-61144609) some 18 days ago -  rcmaehl has simply removed that section from his page_

**Comment by HarshalKudale** [comment] 2021-12-19 02:51
@AveYo The code wasn't hard to understand it's just that I didn't know ps scripting. I have added UseFilter and junction link in my test version.Your script is really good in terms of usability.

As for the table sorry I didn't read that comment 😅. I will update the table ASAP.

**Comment by Yannik** [comment] 2021-12-19 12:00
@HarshalKudale Did you push your test version to a new branch? I couldn't find it.

**Comment by HarshalKudale** [comment] 2021-12-19 12:05
@Yannik not yet. I am completely redesigning setup basically converting it do dashboard. Adding more features like nuking edge ,  making DDG bangs optional. So it will take time . I also removed IFEO backup exe and adding other method to launch edge so that it wont bug with every new update. You can say its going to be at least 2.0 with those update.

**Comment by HarshalKudale** [comment] 2021-12-19 15:33
@Yannik @ferrazpedro @totallygeekdom New release is live. Some features are disabled but it has bugfix and lot of changes. Please check if this fixes the issue regarding Edge update. Please reply with status so that I can close Issue.

Thank you for using NoMoreEdge😛

**Comment by Yannik** [comment] 2021-12-19 15:48
@HarshalKudale I reviewed your code and it looks good to me! I will try it out later.

**Comment by HarshalKudale** [comment] 2021-12-19 16:07
Sure

**Comment by ferrazpedro** [comment] 2021-12-19 16:27
I`ve just tested and it seems to be working fine now! Thanks a lot for the quick fix!

**Comment by HarshalKudale** [comment] 2021-12-19 16:34
> I`ve just tested and it seems to be working fine now! Thanks a lot for the quick fix!

Thank you for confirming . i will close the issue now.

**Closed as completed by HarshalKudale** 2021-12-19 16:34 UTC
Labels: bug

**Comment by Yannik** [comment] 2021-12-19 16:48
@HarshalKudale I tested your new release and found a bug: When selecting DuckDuckGo as search engine, searches do not work at all anymore.

**Comment by Yannik** [comment] 2021-12-19 17:02
@HarshalKudale The problem is that you are checking for `Duckduckgo` [here](https://github.com/HarshalKudale/NoMoreEdge/blob/master/NoMoreEdge.cs#L37), even though you wrote `DuckDuckGo` to registry.

**Comment by HarshalKudale** [comment] 2021-12-19 17:05
I have added new issue for the same. Quick workaround is provided via custom engine query. bug will be fixed in next update.
