### ISSUE TITLE
Edge fail to start after being updated

### ISSUE THREAD

**Issue by chjohans** [HarshalKudale/NoMoreEdge#9] opened 2021-12-15 08:26 UTC
I use Chrome as my default browser, but once in a while, I want to use Edge for something specific.

I've noticed that after installing NoMoreEdge, Edge will stop working (cannot be started at all) every time MS is updating it. And that happens fairly often, so with this installed Edge stops working at all quite often.

A workaround is to uninstall and then install NoMoreEdge again, so far Edge has started to work every time I've done that. But it's a hassle and should not be necessary so please look into a fix for this. Thanks!

**Comment by HarshalKudale** [comment] 2021-12-15 10:50
Thank you for report this issue. This is duplicate of #8 . I need more information on when it stops working. Thank you for providing the information. I will look into it when next edge update arrives. I will close this issue now and update in #8

**Closed as completed by HarshalKudale** 2021-12-15 10:50 UTC
